# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotosVK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod "VK-ios-sdk" 
pod "Alamofire"
  # Pods for PhotosVK

  target 'PhotosVKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotosVKUITests' do
    # Pods for testing
  end

end
